apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: alertmanager-templates
  namespace: monitoring
data:
  email.default.html.tmpl: |-
    {{ define "emaildefaulthtml" }}
    <h3>You have the following alerts:</h3>
    {{ range .Alerts }}
    <p><b>{{.Labels.alertname}}</b>
      <ul>{{ range .Annotations.SortedPairs }}
      <li>{{ .Name }} = {{ .Value }}</li>
      {{ end }}</ul>
      <ul>{{ range .Labels.SortedPairs }}
      <li>{{ .Name }} = {{ .Value }}</li>
      {{ end }}</ul>
      {{ .GeneratorURL }}</p>
    {{ end }}
    {{ end }}

  email.default.txt.tmpl: |-
    {{ define "emaildefaulttext" }}
    You have the following alerts:
    {{ range .Alerts }}
    * {{.Labels.alertname}}
      {{ range .Annotations.SortedPairs }}
      {{ .Name }} = {{ .Value }}
      {{ end }}
      {{ range .Labels.SortedPairs }}
      {{ .Name }} = {{ .Value }}
      {{ end }}
      {{ .GeneratorURL }}
    {{ end }}
    {{ end }}
  slack.tmpl: |
    {{ define "__alert_silence_link" -}}
        {{ .ExternalURL }}/#/silences/new?filter=%7B
        {{- range .CommonLabels.SortedPairs -}}
            {{- if ne .Name "alertname" -}}
                {{- .Name }}%3D"{{- .Value -}}"%2C%20
            {{- end -}}
        {{- end -}}
        alertname%3D"{{ .CommonLabels.alertname }}"%7D
    {{- end }}  
    {{ define "__alert_severity_prefix" -}}
        {{ if ne .Status "firing" -}}
        :lgtm:
        {{- else if eq .Labels.severity "critical" -}}
        :fire:
        {{- else if eq .Labels.severity "warning" -}}
        :warning:
        {{- else -}}
        :question:
        {{- end }}
    {{- end }}

    {{ define "__alert_severity_prefix_title" -}}
        {{ if ne .Status "firing" -}}
        :lgtm:
        {{- else if eq .CommonLabels.severity "critical" -}}
        :fire:
        {{- else if eq .CommonLabels.severity "warning" -}}
        :warning:
        {{- else if eq .CommonLabels.severity "info" -}}
        :information_source:
        {{- else -}}
        :question:
        {{- end }}
    {{- end }}

    {{/* First line of Slack alerts */}}
    {{ define "slack.monzo.title" -}}
        [{{ .Status | toUpper -}}
        {{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end -}}
        ] {{ template "__alert_severity_prefix_title" . }} {{ .CommonLabels.alertname }}
    {{- end }}

    {{/* Color of Slack attachment (appears as line next to alert )*/}}
    {{ define "slack.monzo.color" -}}
        {{ if eq .Status "firing" -}}
            {{ if eq .CommonLabels.severity "warning" -}}
                warning
            {{- else if eq .CommonLabels.severity "critical" -}}
                danger
            {{- else -}}
                #439FE0
            {{- end -}}
        {{ else -}}
        good
        {{- end }}
    {{- end }}

    {{/* The test to display in the alert */}}
    {{ define "slack.monzo.text" -}}
        {{ range .Alerts }}
            {{- if .Annotations.message }}
              {{ "Summary:" }}  {{ .Annotations.message }}
            {{- end }}
            {{- if .Annotations.description }}
                {{ .Annotations.description }}
            {{- end }}
        {{- end }}
    {{- end }}