apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-storage-volume
  namespace: monitoring
  labels:
    usage: prometheus-shared-deployement
spec:
  storageClassName:  default # managed-premium
  capacity:
    storage: 10Gi # Change Me
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/prometheus_home"