apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-volume
  namespace: monitoring
  labels:
    app: prometheus
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default # managed-premium 
  resources:
    requests:
      storage: 10Gi # Change Me